#!/bin/python

# This code will print "Hello, World!" ...
if __name__ == '__main__':
    # store a string in a variable ...
    my_string = "Hello World"
    # print the string ...
    print(my_string)